export const getDemoTruebillResult = () => ({
  items: [
    {
      name: 'ICU Bed Charges (24 hrs)',
      category: 'room',
      charged: 18000,
      expected: 18000,
      status: 'OK',
      reason: 'Aligned with city benchmark for tertiary hospitals',
      riskScore: 8,
      severity: 'none',
      flags: [],
    },
    {
      name: 'Ceftriaxone 1g Injection',
      category: 'medicine',
      charged: 1650,
      expected: 620,
      status: 'FLAGGED',
      reason: 'MRP mismatch - billed amount is significantly above benchmark',
      riskScore: 87,
      severity: 'high',
      flags: ['mrp-overcharge'],
    },
    {
      name: 'Nursing Assessment Fee',
      category: 'consultation',
      charged: 2400,
      expected: 1200,
      status: 'FLAGGED',
      reason: 'Potential duplicate nursing assessment in same billing window',
      riskScore: 72,
      severity: 'medium',
      flags: ['duplicate-charge'],
    },
    {
      name: 'ECG Monitoring',
      category: 'procedure',
      charged: 1800,
      expected: 1500,
      status: 'OK',
      reason: 'Within acceptable variance',
      riskScore: 22,
      severity: 'low',
      flags: [],
    },
  ],
  summary: {
    totalItems: 4,
    okItems: 2,
    flaggedItems: 2,
    totalCharged: 23850,
    avgRiskScore: 47.3,
    extractionQuality: 92,
  },
  extraction: {
    source: 'genai',
    extractionQuality: 92,
    warnings: [],
  },
  ocrText:
    'ICU Bed Charges 18000\nCeftriaxone 1g 1650\nNursing Assessment 2400\nECG Monitoring 1800',
});
